### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by ricardoquesada** [paulscottrobson/junior-emulator#1]
Could you add the steps needed to compile it?

When I type `make` it gets me this error:

```
make -C emulator
make[1]: Entering directory '/opt/src/c256-foenix/junior-emulator/emulator'
make -B -C roms
make[2]: Entering directory '/opt/src/c256-foenix/junior-emulator/emulator/roms'
make -B -C ../../../junior-tinykernel
make[3]: Entering directory '/opt/src/c256-foenix/junior-emulator/emulator/roms'
make[3]: *** ../../../junior-tinykernel: No such file or directory.  Stop.
make[3]: Leaving directory '/opt/src/c256-foenix/junior-emulator/emulator/roms'
make[2]: *** [makefile:9: all] Error 2
make[2]: Leaving directory '/opt/src/c256-foenix/junior-emulator/emulator/roms'
make[1]: *** [makefile:36: prebuild] Error 2
make[1]: Leaving directory '/opt/src/c256-foenix/junior-emulator/emulator'
make: *** [makefile:8: all] Error 2
```

I guess I need to checkout other repos, but which ones?

**Comment by paulscottrobson** [comment]
junior-tinykernel which should be in the same github ; this is loaded in by default at present - both repos should have the same parent directory.

**Comment by paulscottrobson** [comment]
Probably is. It has the tiny kernel built in  - this prints the 1234 (Keyboard booting) and the AA. It then jumps to $8000 and runs whatever is there - it's very primitive to get it started. If you get a basic.rom from the superbasic github, and start it with jr256 basic.rom@8000 it should work. It really needs tidying up, apologies.

**Comment by paulscottrobson** [comment]
Okay - I have tidied it up to make it much easier. 

1) It now lists the repositories needed to build anything in my area - there are six of these , four of mine (emulator, kernel, utilities, basic) and Jessie's old Kernel and PJWs serial uploader, None of these are big,

2) The makefile now has a make run which should boot straight into BASIC. The BASIC reference is in the superbasic repository. Sprites are slightly more complicated as the sprite data needs to be loaded in seperately - there is a workflow for this in superbasic/games - basically it takes assorted PNGs (which can be ripped from others) and combines them together into a sprite file. 

3) I've expanded the notes etc. so they are up to date and a lot clearer.

Cheers, Paul.

**Comment by paulscottrobson** [comment]
Apologies for the bad keyboard response - it was a quick hack to allow me to type but it's not very responsive, I am going to replace it because I now have a Javascript version of the emulator for the website - the hardware has no problem of course :)

**Comment by ricardoquesada** [comment]
Thanks!
